import './js/header';
import './js/mobile-menu';
import './js/hero';
import './js/exercises-left';
import './js/favorites';
//import './js/footer';
import './js/modal';
import './js/modal-rating';
import './js/go-top';
